///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CargaAtencion recording.
    /// </summary>
    [TestModule("502983f3-0571-4c9b-a2be-4f3ff5603381", ModuleType.Recording, 1)]
    public partial class CargaAtencion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static CargaAtencion instance = new CargaAtencion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CargaAtencion()
        {
            FechaInicio = "08072019";
            FechaFin = "08072019";
            NroIdentificacion = "93366092";
            TipoIdentificacion = "CC";
            ValorBruto = "800000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CargaAtencion Instance
        {
            get { return instance; }
        }

#region Variables

        string _FechaInicio;

        /// <summary>
        /// Gets or sets the value of variable FechaInicio.
        /// </summary>
        [TestVariable("7e84670b-00c1-40b7-8578-3e5adea77bee")]
        public string FechaInicio
        {
            get { return _FechaInicio; }
            set { _FechaInicio = value; }
        }

        string _FechaFin;

        /// <summary>
        /// Gets or sets the value of variable FechaFin.
        /// </summary>
        [TestVariable("97ef1d5b-9d82-4749-ba02-f8d1fda522f0")]
        public string FechaFin
        {
            get { return _FechaFin; }
            set { _FechaFin = value; }
        }

        string _TipoIdentificacion;

        /// <summary>
        /// Gets or sets the value of variable TipoIdentificacion.
        /// </summary>
        [TestVariable("5a290b74-ce0a-4ffa-b004-94d9283b6f8b")]
        public string TipoIdentificacion
        {
            get { return _TipoIdentificacion; }
            set { _TipoIdentificacion = value; }
        }

        string _ValorBruto;

        /// <summary>
        /// Gets or sets the value of variable ValorBruto.
        /// </summary>
        [TestVariable("c82aa472-ecb1-40a1-8ecd-26227874e27d")]
        public string ValorBruto
        {
            get { return _ValorBruto; }
            set { _ValorBruto = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NroIdentificacion.
        /// </summary>
        [TestVariable("f64d388b-1df3-44c3-8af1-384a2a37fd63")]
        public string NroIdentificacion
        {
            get { return repo.NroIdentificacion; }
            set { repo.NroIdentificacion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.FechaIni' at Center.", repo.MDIPrincipal.Row1.FechaIniInfo, new RecordItemIndex(0));
            repo.MDIPrincipal.Row1.FechaIni.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.FechaIni' at Center.", repo.MDIPrincipal.Row1.FechaIniInfo, new RecordItemIndex(2));
            repo.MDIPrincipal.Row1.FechaIni.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FechaInicio' with focus on 'MDIPrincipal.Row1.FechaIni'.", repo.MDIPrincipal.Row1.FechaIniInfo, new RecordItemIndex(3));
            repo.MDIPrincipal.Row1.FechaIni.PressKeys(FechaInicio);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.FechaFin' at Center.", repo.MDIPrincipal.Row1.FechaFinInfo, new RecordItemIndex(4));
            repo.MDIPrincipal.Row1.FechaFin.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FechaFin' with focus on 'MDIPrincipal.Row1.FechaFin'.", repo.MDIPrincipal.Row1.FechaFinInfo, new RecordItemIndex(5));
            repo.MDIPrincipal.Row1.FechaFin.PressKeys(FechaFin);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.NumeroIdentificacion' at Center.", repo.MDIPrincipal.Row1.NumeroIdentificacionInfo, new RecordItemIndex(7));
            repo.MDIPrincipal.Row1.NumeroIdentificacion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NroIdentificacion'.", new RecordItemIndex(8));
            Keyboard.Press(NroIdentificacion);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.TipoDeIdentificacionId' at Center.", repo.MDIPrincipal.Row1.TipoDeIdentificacionIdInfo, new RecordItemIndex(9));
            repo.MDIPrincipal.Row1.TipoDeIdentificacionId.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipoIdentificacion'.", new RecordItemIndex(10));
            Keyboard.Press(TipoIdentificacion);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.PrimerApellido' at Center.", repo.MDIPrincipal.Row1.PrimerApellidoInfo, new RecordItemIndex(11));
            repo.MDIPrincipal.Row1.PrimerApellido.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(12));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'FFFF'.", new RecordItemIndex(13));
            Keyboard.Press("FFFF");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'MDIPrincipal.Row1.NombreContenido'", repo.MDIPrincipal.Row1.NombreContenidoInfo, new ActionTimeout(5000), new RecordItemIndex(14));
            repo.MDIPrincipal.Row1.NombreContenidoInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.ValorBruto' at Center.", repo.MDIPrincipal.Row1.ValorBrutoInfo, new RecordItemIndex(15));
            repo.MDIPrincipal.Row1.ValorBruto.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ValorBruto'.", new RecordItemIndex(16));
            Keyboard.Press(ValorBruto);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.ValorNeto' at Center.", repo.MDIPrincipal.Row1.ValorNetoInfo, new RecordItemIndex(17));
            repo.MDIPrincipal.Row1.ValorNeto.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ValorBruto'.", new RecordItemIndex(18));
            Keyboard.Press(ValorBruto);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
