///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CargaServiciosMasiva recording.
    /// </summary>
    [TestModule("fb1841dc-8330-4601-b41a-b5dafeb987c6", ModuleType.Recording, 1)]
    public partial class CargaServiciosMasiva : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static CargaServiciosMasiva instance = new CargaServiciosMasiva();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CargaServiciosMasiva()
        {
            NroIdentificacionOriginal = "";
            NroIdentificacion = "";
            CodServicio = "";
            VlrUnitario = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CargaServiciosMasiva Instance
        {
            get { return instance; }
        }

#region Variables

        string _NroIdentificacionOriginal;

        /// <summary>
        /// Gets or sets the value of variable NroIdentificacionOriginal.
        /// </summary>
        [TestVariable("43733c06-57a6-4933-bb65-31b0493a90b7")]
        public string NroIdentificacionOriginal
        {
            get { return _NroIdentificacionOriginal; }
            set { _NroIdentificacionOriginal = value; }
        }

        string _VlrUnitario;

        /// <summary>
        /// Gets or sets the value of variable VlrUnitario.
        /// </summary>
        [TestVariable("db6b2690-02a0-42c6-a1e2-bfa65f6cb445")]
        public string VlrUnitario
        {
            get { return _VlrUnitario; }
            set { _VlrUnitario = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable CodServicio.
        /// </summary>
        [TestVariable("e116240f-9a1b-4346-8971-c3e9addcfe98")]
        public string CodServicio
        {
            get { return repo.CodServicio; }
            set { repo.CodServicio = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NroIdentificacion.
        /// </summary>
        [TestVariable("4607ff8a-7e4e-4fb5-a793-fd5b9aed10bf")]
        public string NroIdentificacion
        {
            get { return repo.NroIdentificacion; }
            set { repo.NroIdentificacion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            CargaServicios();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
