///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CuentasMedicas_SanitasRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("fde6ab7f-276c-47f2-ae51-f84d2cd2116c")]
    public partial class CuentasMedicas_SanitasRepository : RepoGenBaseFolder
    {
        static CuentasMedicas_SanitasRepository instance = new CuentasMedicas_SanitasRepository();
        CuentasMedicas_SanitasRepositoryFolders.MDIPrincipalAppFolder _mdiprincipal;
        CuentasMedicas_SanitasRepositoryFolders.IQCuentasMedicasAppFolder _iqcuentasmedicas;
        CuentasMedicas_SanitasRepositoryFolders.List1000AppFolder _list1000;
        CuentasMedicas_SanitasRepositoryFolders.FrmLoginAppFolder _frmlogin;
        CuentasMedicas_SanitasRepositoryFolders.AsociacionAnexos_COFAppFolder _asociacionanexos_cof;
        CuentasMedicas_SanitasRepositoryFolders.Advertencia_COFAppFolder _advertencia_cof;
        CuentasMedicas_SanitasRepositoryFolders.FrmReprocesoAppFolder _frmreproceso;

        /// <summary>
        /// Gets the singleton class instance representing the CuentasMedicas_SanitasRepository element repository.
        /// </summary>
        [RepositoryFolder("fde6ab7f-276c-47f2-ae51-f84d2cd2116c")]
        public static CuentasMedicas_SanitasRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CuentasMedicas_SanitasRepository() 
            : base("CuentasMedicas_SanitasRepository", "/", null, 0, false, "fde6ab7f-276c-47f2-ae51-f84d2cd2116c", ".\\RepositoryImages\\CuentasMedicas_SanitasRepositoryfde6ab7f.rximgres")
        {
            _mdiprincipal = new CuentasMedicas_SanitasRepositoryFolders.MDIPrincipalAppFolder(this);
            _iqcuentasmedicas = new CuentasMedicas_SanitasRepositoryFolders.IQCuentasMedicasAppFolder(this);
            _list1000 = new CuentasMedicas_SanitasRepositoryFolders.List1000AppFolder(this);
            _frmlogin = new CuentasMedicas_SanitasRepositoryFolders.FrmLoginAppFolder(this);
            _asociacionanexos_cof = new CuentasMedicas_SanitasRepositoryFolders.AsociacionAnexos_COFAppFolder(this);
            _advertencia_cof = new CuentasMedicas_SanitasRepositoryFolders.Advertencia_COFAppFolder(this);
            _frmreproceso = new CuentasMedicas_SanitasRepositoryFolders.FrmReprocesoAppFolder(this);
        }

#region Variables

        string _MenuItem = "Captura Atenciones y Servicios";

        /// <summary>
        /// Gets or sets the value of variable MenuItem.
        /// </summary>
        [TestVariable("aabc01ea-ec93-4de2-ab96-733731c89f7e")]
        public string MenuItem
        {
            get { return _MenuItem; }
            set { _MenuItem = value; }
        }

        string _ItemProducto = "Cuentas Medicas";

        /// <summary>
        /// Gets or sets the value of variable ItemProducto.
        /// </summary>
        [TestVariable("12f92637-d732-4177-a3da-8a9594b97f83")]
        public string ItemProducto
        {
            get { return _ItemProducto; }
            set { _ItemProducto = value; }
        }

        string _CodServicio = "890702";

        /// <summary>
        /// Gets or sets the value of variable CodServicio.
        /// </summary>
        [TestVariable("1c08caca-7405-4485-a517-a7b7060789e7")]
        public string CodServicio
        {
            get { return _CodServicio; }
            set { _CodServicio = value; }
        }

        string _NroIdentificacion = "51876614";

        /// <summary>
        /// Gets or sets the value of variable NroIdentificacion.
        /// </summary>
        [TestVariable("6a6a704e-8bd9-4f2f-a42d-e2132a8328ba")]
        public string NroIdentificacion
        {
            get { return _NroIdentificacion; }
            set { _NroIdentificacion = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fde6ab7f-276c-47f2-ae51-f84d2cd2116c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MDIPrincipal folder.
        /// </summary>
        [RepositoryFolder("edaee240-1d6d-4732-b9fe-38615680e321")]
        public virtual CuentasMedicas_SanitasRepositoryFolders.MDIPrincipalAppFolder MDIPrincipal
        {
            get { return _mdiprincipal; }
        }

        /// <summary>
        /// The IQCuentasMedicas folder.
        /// </summary>
        [RepositoryFolder("2cdfddb8-5b33-4193-ad6d-3fae17122010")]
        public virtual CuentasMedicas_SanitasRepositoryFolders.IQCuentasMedicasAppFolder IQCuentasMedicas
        {
            get { return _iqcuentasmedicas; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("f03d404b-fe99-494b-afba-eb9d650fa9f8")]
        public virtual CuentasMedicas_SanitasRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The FrmLogin folder.
        /// </summary>
        [RepositoryFolder("f0389836-0c1b-49cb-9224-df4011a1986a")]
        public virtual CuentasMedicas_SanitasRepositoryFolders.FrmLoginAppFolder FrmLogin
        {
            get { return _frmlogin; }
        }

        /// <summary>
        /// The AsociacionAnexos_COF folder.
        /// </summary>
        [RepositoryFolder("813662be-95b1-4d00-b384-4b5028a6b090")]
        public virtual CuentasMedicas_SanitasRepositoryFolders.AsociacionAnexos_COFAppFolder AsociacionAnexos_COF
        {
            get { return _asociacionanexos_cof; }
        }

        /// <summary>
        /// The Advertencia_COF folder.
        /// </summary>
        [RepositoryFolder("0b173e44-3415-4599-9183-d12ff220b9f2")]
        public virtual CuentasMedicas_SanitasRepositoryFolders.Advertencia_COFAppFolder Advertencia_COF
        {
            get { return _advertencia_cof; }
        }

        /// <summary>
        /// The FrmReproceso folder.
        /// </summary>
        [RepositoryFolder("cb7a21fc-2488-4452-b687-17aa99985734")]
        public virtual CuentasMedicas_SanitasRepositoryFolders.FrmReprocesoAppFolder FrmReproceso
        {
            get { return _frmreproceso; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CuentasMedicas_SanitasRepositoryFolders
    {
        /// <summary>
        /// The MDIPrincipalAppFolder folder.
        /// </summary>
        [RepositoryFolder("edaee240-1d6d-4732-b9fe-38615680e321")]
        public partial class MDIPrincipalAppFolder : RepoGenBaseFolder
        {
            CuentasMedicas_SanitasRepositoryFolders.Row1Folder _row1;
            RepoItemInfo _codigoservicioaddrowInfo;
            RepoItemInfo _codigoserviciotemplateInfo;
            RepoItemInfo _vlrunitarioInfo;
            RepoItemInfo _btnguardarInfo;
            RepoItemInfo _archivoInfo;
            RepoItemInfo _cboproductosInfo;
            RepoItemInfo _btninicioInfo;
            RepoItemInfo _btnterminarInfo;
            RepoItemInfo _nroidentificacionInfo;
            RepoItemInfo _lblopcionesInfo;

            /// <summary>
            /// Creates a new MDIPrincipal  folder.
            /// </summary>
            public MDIPrincipalAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MDIPrincipal", "/form[@controlname='MDIPrincipal']", parentFolder, 30000, null, true, "edaee240-1d6d-4732-b9fe-38615680e321", "")
            {
                _row1 = new CuentasMedicas_SanitasRepositoryFolders.Row1Folder(this);
                _codigoservicioaddrowInfo = new RepoItemInfo(this, "CodigoServicioAddRow", "element[@controltypename='MdiClient']/form[@controlname='FrmCapturaAtencionesServiciosIII']/container[@controlname='SplBotones']/container[@controlname='panel1']/?/?/container[@controlname='panel2']/?/?/container[@controlname='panel2']/?/?/tabpage[@controlname='AtencionesYServicios']//element[@controlname='GRDSERVICIOS']/table[@accessiblename='ultraGrid2']/row[@accessiblename='Add Row']/cell[@accessiblename='CodigoServicio']", 30000, null, "b86472da-4db0-4353-95d8-4961c4b79e26");
                _codigoserviciotemplateInfo = new RepoItemInfo(this, "CodigoServicioTemplate", "?/?/form[@controlname='FrmCapturaAtencionesServiciosIII']/container[@controlname='SplBotones']/container[@controlname='panel1']/?/?/container[@controlname='panel2']//tabpage[@controlname='AtencionesYServicios']/?/?/container[@controlname='panel2']/?/?/container[@controlname='panel2']//table[@accessiblename='ultraGrid2']/row[@accessiblename='Template Add Row']/cell[@accessiblename='CodigoServicio']", 30000, null, "b12aaf12-8e37-4f99-ad76-596a4ff26ab9");
                _vlrunitarioInfo = new RepoItemInfo(this, "VlrUnitario", "?/?/form[@controlname='FrmCapturaAtencionesServiciosIII']/container[@controlname='SplBotones']/container[@controlname='panel1']/?/?/container[@controlname='panel2']//tabpage[@controlname='AtencionesYServicios']/?/?/container[@controlname='panel2']/?/?/container[@controlname='panel2']//table[@accessiblename='ultraGrid2']//cell[@accessiblevalue=$CodServicio]/../cell[@accessiblename='Vlr. Unitario' and @accessiblevalue~'[0-9]+']", 30000, null, "bc1b1a52-e6fe-4672-9be4-80eaee1060a0");
                _btnguardarInfo = new RepoItemInfo(this, "BtnGuardar", "?/?/form[@controlname='FrmCapturaAtencionesServiciosIII']/container[@controlname='SplBotones']/?/?/button[@controlname='btnGuardar']", 30000, null, "fb6d5e83-5b62-4824-8c8e-17c7489a9bc3");
                _archivoInfo = new RepoItemInfo(this, "Archivo", "?/?/menuitem[@accessiblename='Archivo']", 30000, null, "baf53eed-7647-4e62-8f9c-8343162e3fd2");
                _cboproductosInfo = new RepoItemInfo(this, "CboProductos", ".//combobox[@controlname='cboProductos']", 30000, null, "9e2165ba-b730-4d63-9f67-3746518cf82b");
                _btninicioInfo = new RepoItemInfo(this, "BtnInicio", ".//button[@controlname>'btnInici']", 30000, null, "a6488d31-7098-482e-8c06-f2645b14ccdb");
                _btnterminarInfo = new RepoItemInfo(this, "BtnTerminar", ".//button[@controlname='btnTerminar' or @controlname='btnSalir']", 30000, null, "8e94e693-0bd4-464a-8e4c-e49e7bdfed55");
                _nroidentificacionInfo = new RepoItemInfo(this, "NroIdentificacion", "?/?/form[@controlname='FrmAsociacionAnexosII']//table[@controlname='dgvAtenciones']//cell[@accessiblename>'Numero de Identificacion' and @accessiblevalue=$NroIdentificacion]", 30000, null, "5a927909-bfaf-4fe4-9320-400e30aab31f");
                _lblopcionesInfo = new RepoItemInfo(this, "LblOpciones", "?/?/form[@controlname='FrmAsociacionAnexosII']/?/?/text[@controlname='lblOpciones']", 30000, null, "179fcefb-fb28-410f-bd1e-db6a91e0737e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("edaee240-1d6d-4732-b9fe-38615680e321")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("edaee240-1d6d-4732-b9fe-38615680e321")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CodigoServicioAddRow item.
            /// </summary>
            [RepositoryItem("b86472da-4db0-4353-95d8-4961c4b79e26")]
            public virtual Ranorex.Cell CodigoServicioAddRow
            {
                get
                {
                    return _codigoservicioaddrowInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CodigoServicioAddRow item info.
            /// </summary>
            [RepositoryItemInfo("b86472da-4db0-4353-95d8-4961c4b79e26")]
            public virtual RepoItemInfo CodigoServicioAddRowInfo
            {
                get
                {
                    return _codigoservicioaddrowInfo;
                }
            }

            /// <summary>
            /// The CodigoServicioTemplate item.
            /// </summary>
            [RepositoryItem("b12aaf12-8e37-4f99-ad76-596a4ff26ab9")]
            public virtual Ranorex.Cell CodigoServicioTemplate
            {
                get
                {
                    return _codigoserviciotemplateInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CodigoServicioTemplate item info.
            /// </summary>
            [RepositoryItemInfo("b12aaf12-8e37-4f99-ad76-596a4ff26ab9")]
            public virtual RepoItemInfo CodigoServicioTemplateInfo
            {
                get
                {
                    return _codigoserviciotemplateInfo;
                }
            }

            /// <summary>
            /// The VlrUnitario item.
            /// </summary>
            [RepositoryItem("bc1b1a52-e6fe-4672-9be4-80eaee1060a0")]
            public virtual Ranorex.Cell VlrUnitario
            {
                get
                {
                    return _vlrunitarioInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The VlrUnitario item info.
            /// </summary>
            [RepositoryItemInfo("bc1b1a52-e6fe-4672-9be4-80eaee1060a0")]
            public virtual RepoItemInfo VlrUnitarioInfo
            {
                get
                {
                    return _vlrunitarioInfo;
                }
            }

            /// <summary>
            /// The BtnGuardar item.
            /// </summary>
            [RepositoryItem("fb6d5e83-5b62-4824-8c8e-17c7489a9bc3")]
            public virtual Ranorex.Button BtnGuardar
            {
                get
                {
                    return _btnguardarInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnGuardar item info.
            /// </summary>
            [RepositoryItemInfo("fb6d5e83-5b62-4824-8c8e-17c7489a9bc3")]
            public virtual RepoItemInfo BtnGuardarInfo
            {
                get
                {
                    return _btnguardarInfo;
                }
            }

            /// <summary>
            /// The Archivo item.
            /// </summary>
            [RepositoryItem("baf53eed-7647-4e62-8f9c-8343162e3fd2")]
            public virtual Ranorex.MenuItem Archivo
            {
                get
                {
                    return _archivoInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Archivo item info.
            /// </summary>
            [RepositoryItemInfo("baf53eed-7647-4e62-8f9c-8343162e3fd2")]
            public virtual RepoItemInfo ArchivoInfo
            {
                get
                {
                    return _archivoInfo;
                }
            }

            /// <summary>
            /// The CboProductos item.
            /// </summary>
            [RepositoryItem("9e2165ba-b730-4d63-9f67-3746518cf82b")]
            public virtual Ranorex.ComboBox CboProductos
            {
                get
                {
                    return _cboproductosInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CboProductos item info.
            /// </summary>
            [RepositoryItemInfo("9e2165ba-b730-4d63-9f67-3746518cf82b")]
            public virtual RepoItemInfo CboProductosInfo
            {
                get
                {
                    return _cboproductosInfo;
                }
            }

            /// <summary>
            /// The BtnInicio item.
            /// </summary>
            [RepositoryItem("a6488d31-7098-482e-8c06-f2645b14ccdb")]
            public virtual Ranorex.Button BtnInicio
            {
                get
                {
                    return _btninicioInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnInicio item info.
            /// </summary>
            [RepositoryItemInfo("a6488d31-7098-482e-8c06-f2645b14ccdb")]
            public virtual RepoItemInfo BtnInicioInfo
            {
                get
                {
                    return _btninicioInfo;
                }
            }

            /// <summary>
            /// The BtnTerminar item.
            /// </summary>
            [RepositoryItem("8e94e693-0bd4-464a-8e4c-e49e7bdfed55")]
            public virtual Ranorex.Button BtnTerminar
            {
                get
                {
                    return _btnterminarInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnTerminar item info.
            /// </summary>
            [RepositoryItemInfo("8e94e693-0bd4-464a-8e4c-e49e7bdfed55")]
            public virtual RepoItemInfo BtnTerminarInfo
            {
                get
                {
                    return _btnterminarInfo;
                }
            }

            /// <summary>
            /// The NroIdentificacion item.
            /// </summary>
            [RepositoryItem("5a927909-bfaf-4fe4-9320-400e30aab31f")]
            public virtual Ranorex.Cell NroIdentificacion
            {
                get
                {
                    return _nroidentificacionInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NroIdentificacion item info.
            /// </summary>
            [RepositoryItemInfo("5a927909-bfaf-4fe4-9320-400e30aab31f")]
            public virtual RepoItemInfo NroIdentificacionInfo
            {
                get
                {
                    return _nroidentificacionInfo;
                }
            }

            /// <summary>
            /// The LblOpciones item.
            /// </summary>
            [RepositoryItem("179fcefb-fb28-410f-bd1e-db6a91e0737e")]
            public virtual Ranorex.Text LblOpciones
            {
                get
                {
                    return _lblopcionesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblOpciones item info.
            /// </summary>
            [RepositoryItemInfo("179fcefb-fb28-410f-bd1e-db6a91e0737e")]
            public virtual RepoItemInfo LblOpcionesInfo
            {
                get
                {
                    return _lblopcionesInfo;
                }
            }

            /// <summary>
            /// The Row1 folder.
            /// </summary>
            [RepositoryFolder("dcf03851-8155-4682-be1c-00d80b1e6d57")]
            public virtual CuentasMedicas_SanitasRepositoryFolders.Row1Folder Row1
            {
                get { return _row1; }
            }
        }

        /// <summary>
        /// The Row1Folder folder.
        /// </summary>
        [RepositoryFolder("dcf03851-8155-4682-be1c-00d80b1e6d57")]
        public partial class Row1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _fechafinInfo;
            RepoItemInfo _fechainiInfo;
            RepoItemInfo _numeroidentificacionInfo;
            RepoItemInfo _tipodeidentificacionidInfo;
            RepoItemInfo _primerapellidoInfo;
            RepoItemInfo _segundoapellidoInfo;
            RepoItemInfo _nombresInfo;
            RepoItemInfo _nombrecontenidoInfo;
            RepoItemInfo _valorbrutoInfo;
            RepoItemInfo _valornetoInfo;

            /// <summary>
            /// Creates a new Row1  folder.
            /// </summary>
            public Row1Folder(RepoGenBaseFolder parentFolder) :
                    base("Row1", "?/?/form[@controlname='FrmCapturaAtencionesServiciosIII']/container[@controlname='SplBotones']/container[@controlname='panel1']/?/?/container[@controlname='panel2']//tabpage[@controlname='AtencionesYServicios']/?/?/container[@controlname='panel2']/?/?/container[@controlname='panel1']//table[@accessiblename='ultraGrid2']/row[@accessiblename='row 1']", parentFolder, 30000, null, false, "dcf03851-8155-4682-be1c-00d80b1e6d57", "")
            {
                _fechafinInfo = new RepoItemInfo(this, "FechaFin", "cell[@accessiblename='Fecha Fin.']", 30000, null, "e6744475-5293-4aff-896f-43185e1c2b29");
                _fechainiInfo = new RepoItemInfo(this, "FechaIni", "cell[@accessiblename='Fecha Ini.']", 30000, null, "e56bbf30-2c68-4fd6-9d8e-9d8115abd33d");
                _numeroidentificacionInfo = new RepoItemInfo(this, "NumeroIdentificacion", "cell[@accessiblename='NumeroIdentificacion']", 30000, null, "c167725d-340c-4719-bc1e-04cc0363728b");
                _tipodeidentificacionidInfo = new RepoItemInfo(this, "TipoDeIdentificacionId", "cell[@accessiblename='TipoDeIdentificacion_id']", 30000, null, "8fa53504-3797-4532-bc85-621c4bcb1993");
                _primerapellidoInfo = new RepoItemInfo(this, "PrimerApellido", "cell[@accessiblename='PrimerApellido']", 30000, null, "95e58c19-6ca0-4bfd-bbc0-9ba153afdc17");
                _segundoapellidoInfo = new RepoItemInfo(this, "SegundoApellido", "cell[@accessiblename='SegundoApellido']", 30000, null, "a7ff7fb8-d7fa-4063-8377-1509bd7b19b1");
                _nombresInfo = new RepoItemInfo(this, "Nombres", "cell[@accessiblename='Nombres']", 30000, null, "84e7a1a0-5622-449f-b430-5a6d02e63bd8");
                _nombrecontenidoInfo = new RepoItemInfo(this, "NombreContenido", "cell[@accessiblename='Nombres' and @accessiblevalue~'[A-Z]+']", 30000, null, "c9969a50-bed2-4d6d-8d93-fc9fb1b305b3");
                _valorbrutoInfo = new RepoItemInfo(this, "ValorBruto", "cell[@accessiblename='ValorBruto']", 30000, null, "952263fd-84fe-4a7c-88f2-d63639c99b75");
                _valornetoInfo = new RepoItemInfo(this, "ValorNeto", "cell[@accessiblename='Valor Neto']", 30000, null, "d24aa01d-6bbe-4ab0-92cf-6fd7823e41bc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dcf03851-8155-4682-be1c-00d80b1e6d57")]
            public virtual Ranorex.Row Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Row>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dcf03851-8155-4682-be1c-00d80b1e6d57")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FechaFin item.
            /// </summary>
            [RepositoryItem("e6744475-5293-4aff-896f-43185e1c2b29")]
            public virtual Ranorex.Cell FechaFin
            {
                get
                {
                    return _fechafinInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The FechaFin item info.
            /// </summary>
            [RepositoryItemInfo("e6744475-5293-4aff-896f-43185e1c2b29")]
            public virtual RepoItemInfo FechaFinInfo
            {
                get
                {
                    return _fechafinInfo;
                }
            }

            /// <summary>
            /// The FechaIni item.
            /// </summary>
            [RepositoryItem("e56bbf30-2c68-4fd6-9d8e-9d8115abd33d")]
            public virtual Ranorex.Cell FechaIni
            {
                get
                {
                    return _fechainiInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The FechaIni item info.
            /// </summary>
            [RepositoryItemInfo("e56bbf30-2c68-4fd6-9d8e-9d8115abd33d")]
            public virtual RepoItemInfo FechaIniInfo
            {
                get
                {
                    return _fechainiInfo;
                }
            }

            /// <summary>
            /// The NumeroIdentificacion item.
            /// </summary>
            [RepositoryItem("c167725d-340c-4719-bc1e-04cc0363728b")]
            public virtual Ranorex.Cell NumeroIdentificacion
            {
                get
                {
                    return _numeroidentificacionInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NumeroIdentificacion item info.
            /// </summary>
            [RepositoryItemInfo("c167725d-340c-4719-bc1e-04cc0363728b")]
            public virtual RepoItemInfo NumeroIdentificacionInfo
            {
                get
                {
                    return _numeroidentificacionInfo;
                }
            }

            /// <summary>
            /// The TipoDeIdentificacionId item.
            /// </summary>
            [RepositoryItem("8fa53504-3797-4532-bc85-621c4bcb1993")]
            public virtual Ranorex.Cell TipoDeIdentificacionId
            {
                get
                {
                    return _tipodeidentificacionidInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The TipoDeIdentificacionId item info.
            /// </summary>
            [RepositoryItemInfo("8fa53504-3797-4532-bc85-621c4bcb1993")]
            public virtual RepoItemInfo TipoDeIdentificacionIdInfo
            {
                get
                {
                    return _tipodeidentificacionidInfo;
                }
            }

            /// <summary>
            /// The PrimerApellido item.
            /// </summary>
            [RepositoryItem("95e58c19-6ca0-4bfd-bbc0-9ba153afdc17")]
            public virtual Ranorex.Cell PrimerApellido
            {
                get
                {
                    return _primerapellidoInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The PrimerApellido item info.
            /// </summary>
            [RepositoryItemInfo("95e58c19-6ca0-4bfd-bbc0-9ba153afdc17")]
            public virtual RepoItemInfo PrimerApellidoInfo
            {
                get
                {
                    return _primerapellidoInfo;
                }
            }

            /// <summary>
            /// The SegundoApellido item.
            /// </summary>
            [RepositoryItem("a7ff7fb8-d7fa-4063-8377-1509bd7b19b1")]
            public virtual Ranorex.Cell SegundoApellido
            {
                get
                {
                    return _segundoapellidoInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The SegundoApellido item info.
            /// </summary>
            [RepositoryItemInfo("a7ff7fb8-d7fa-4063-8377-1509bd7b19b1")]
            public virtual RepoItemInfo SegundoApellidoInfo
            {
                get
                {
                    return _segundoapellidoInfo;
                }
            }

            /// <summary>
            /// The Nombres item.
            /// </summary>
            [RepositoryItem("84e7a1a0-5622-449f-b430-5a6d02e63bd8")]
            public virtual Ranorex.Cell Nombres
            {
                get
                {
                    return _nombresInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Nombres item info.
            /// </summary>
            [RepositoryItemInfo("84e7a1a0-5622-449f-b430-5a6d02e63bd8")]
            public virtual RepoItemInfo NombresInfo
            {
                get
                {
                    return _nombresInfo;
                }
            }

            /// <summary>
            /// The NombreContenido item.
            /// </summary>
            [RepositoryItem("c9969a50-bed2-4d6d-8d93-fc9fb1b305b3")]
            public virtual Ranorex.Cell NombreContenido
            {
                get
                {
                    return _nombrecontenidoInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NombreContenido item info.
            /// </summary>
            [RepositoryItemInfo("c9969a50-bed2-4d6d-8d93-fc9fb1b305b3")]
            public virtual RepoItemInfo NombreContenidoInfo
            {
                get
                {
                    return _nombrecontenidoInfo;
                }
            }

            /// <summary>
            /// The ValorBruto item.
            /// </summary>
            [RepositoryItem("952263fd-84fe-4a7c-88f2-d63639c99b75")]
            public virtual Ranorex.Cell ValorBruto
            {
                get
                {
                    return _valorbrutoInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ValorBruto item info.
            /// </summary>
            [RepositoryItemInfo("952263fd-84fe-4a7c-88f2-d63639c99b75")]
            public virtual RepoItemInfo ValorBrutoInfo
            {
                get
                {
                    return _valorbrutoInfo;
                }
            }

            /// <summary>
            /// The ValorNeto item.
            /// </summary>
            [RepositoryItem("d24aa01d-6bbe-4ab0-92cf-6fd7823e41bc")]
            public virtual Ranorex.Cell ValorNeto
            {
                get
                {
                    return _valornetoInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ValorNeto item info.
            /// </summary>
            [RepositoryItemInfo("d24aa01d-6bbe-4ab0-92cf-6fd7823e41bc")]
            public virtual RepoItemInfo ValorNetoInfo
            {
                get
                {
                    return _valornetoInfo;
                }
            }
        }

        /// <summary>
        /// The IQCuentasMedicasAppFolder folder.
        /// </summary>
        [RepositoryFolder("2cdfddb8-5b33-4193-ad6d-3fae17122010")]
        public partial class IQCuentasMedicasAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _capturaatencionesyserviciosInfo;

            /// <summary>
            /// Creates a new IQCuentasMedicas  folder.
            /// </summary>
            public IQCuentasMedicasAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IQCuentasMedicas", "/contextmenu[@processname='IQ.CuentasMedicas']", parentFolder, 30000, null, true, "2cdfddb8-5b33-4193-ad6d-3fae17122010", "")
            {
                _capturaatencionesyserviciosInfo = new RepoItemInfo(this, "CapturaAtencionesYServicios", "menuitem[@accessiblename=$MenuItem]", 30000, null, "4de552e5-3b5a-4214-bc21-c356990f19bd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2cdfddb8-5b33-4193-ad6d-3fae17122010")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2cdfddb8-5b33-4193-ad6d-3fae17122010")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CapturaAtencionesYServicios item.
            /// </summary>
            [RepositoryItem("4de552e5-3b5a-4214-bc21-c356990f19bd")]
            public virtual Ranorex.MenuItem CapturaAtencionesYServicios
            {
                get
                {
                    return _capturaatencionesyserviciosInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The CapturaAtencionesYServicios item info.
            /// </summary>
            [RepositoryItemInfo("4de552e5-3b5a-4214-bc21-c356990f19bd")]
            public virtual RepoItemInfo CapturaAtencionesYServiciosInfo
            {
                get
                {
                    return _capturaatencionesyserviciosInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("f03d404b-fe99-494b-afba-eb9d650fa9f8")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cuentasmedicasInfo;
            RepoItemInfo _listitem1documentoprincipalInfo;
            RepoItemInfo _cuentasmedicas1Info;
            RepoItemInfo _sanitasInfo;
            RepoItemInfo _cuentasmedicas2Info;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "f03d404b-fe99-494b-afba-eb9d650fa9f8", "")
            {
                _cuentasmedicasInfo = new RepoItemInfo(this, "CuentasMedicas", "listitem[@text=$ItemProducto]", 30000, null, "17e87f6a-676b-4df3-9446-dfea35536486");
                _listitem1documentoprincipalInfo = new RepoItemInfo(this, "ListItem1DocumentoPrincipal", "listitem[@text='1 | DocumentoPrincipal']", 30000, null, "9778efd7-89c7-458d-afec-4a9e6230cc48");
                _cuentasmedicas1Info = new RepoItemInfo(this, "CuentasMedicas1", "listitem[@text='Cuentas Medicas']", 30000, null, "da0a5317-30c6-461f-9885-5b971e4f7b1f");
                _sanitasInfo = new RepoItemInfo(this, "SANITAS", "listitem[@text='SANITAS']", 30000, null, "4e259f94-25fa-4e14-83ee-ce62132932e0");
                _cuentasmedicas2Info = new RepoItemInfo(this, "CuentasMedicas2", "listitem[@text='Cuentas Medicas']", 30000, null, "8aff9199-c31e-4187-a024-b2d876b3f1f7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f03d404b-fe99-494b-afba-eb9d650fa9f8")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f03d404b-fe99-494b-afba-eb9d650fa9f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CuentasMedicas item.
            /// </summary>
            [RepositoryItem("17e87f6a-676b-4df3-9446-dfea35536486")]
            public virtual Ranorex.ListItem CuentasMedicas
            {
                get
                {
                    return _cuentasmedicasInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The CuentasMedicas item info.
            /// </summary>
            [RepositoryItemInfo("17e87f6a-676b-4df3-9446-dfea35536486")]
            public virtual RepoItemInfo CuentasMedicasInfo
            {
                get
                {
                    return _cuentasmedicasInfo;
                }
            }

            /// <summary>
            /// The ListItem1DocumentoPrincipal item.
            /// </summary>
            [RepositoryItem("9778efd7-89c7-458d-afec-4a9e6230cc48")]
            public virtual Ranorex.ListItem ListItem1DocumentoPrincipal
            {
                get
                {
                    return _listitem1documentoprincipalInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem1DocumentoPrincipal item info.
            /// </summary>
            [RepositoryItemInfo("9778efd7-89c7-458d-afec-4a9e6230cc48")]
            public virtual RepoItemInfo ListItem1DocumentoPrincipalInfo
            {
                get
                {
                    return _listitem1documentoprincipalInfo;
                }
            }

            /// <summary>
            /// The CuentasMedicas1 item.
            /// </summary>
            [RepositoryItem("da0a5317-30c6-461f-9885-5b971e4f7b1f")]
            public virtual Ranorex.ListItem CuentasMedicas1
            {
                get
                {
                    return _cuentasmedicas1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The CuentasMedicas1 item info.
            /// </summary>
            [RepositoryItemInfo("da0a5317-30c6-461f-9885-5b971e4f7b1f")]
            public virtual RepoItemInfo CuentasMedicas1Info
            {
                get
                {
                    return _cuentasmedicas1Info;
                }
            }

            /// <summary>
            /// The SANITAS item.
            /// </summary>
            [RepositoryItem("4e259f94-25fa-4e14-83ee-ce62132932e0")]
            public virtual Ranorex.ListItem SANITAS
            {
                get
                {
                    return _sanitasInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SANITAS item info.
            /// </summary>
            [RepositoryItemInfo("4e259f94-25fa-4e14-83ee-ce62132932e0")]
            public virtual RepoItemInfo SANITASInfo
            {
                get
                {
                    return _sanitasInfo;
                }
            }

            /// <summary>
            /// The CuentasMedicas2 item.
            /// </summary>
            [RepositoryItem("8aff9199-c31e-4187-a024-b2d876b3f1f7")]
            public virtual Ranorex.ListItem CuentasMedicas2
            {
                get
                {
                    return _cuentasmedicas2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The CuentasMedicas2 item info.
            /// </summary>
            [RepositoryItemInfo("8aff9199-c31e-4187-a024-b2d876b3f1f7")]
            public virtual RepoItemInfo CuentasMedicas2Info
            {
                get
                {
                    return _cuentasmedicas2Info;
                }
            }
        }

        /// <summary>
        /// The FrmLoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("f0389836-0c1b-49cb-9224-df4011a1986a")]
        public partial class FrmLoginAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtloginInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _cmbcompaniaInfo;
            RepoItemInfo _cmblineaInfo;
            RepoItemInfo _cmdaceptarInfo;

            /// <summary>
            /// Creates a new FrmLogin  folder.
            /// </summary>
            public FrmLoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmLogin", "/form[@controlname='FrmLogin']", parentFolder, 30000, null, true, "f0389836-0c1b-49cb-9224-df4011a1986a", "")
            {
                _txtloginInfo = new RepoItemInfo(this, "TxtLogin", "text[@controlname='txtLogin']", 30000, null, "2e296aac-d056-45f1-8256-85d423b26d33");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", "text[@controlname='txtPassword']", 30000, null, "61f9105f-2e43-4ada-9a84-edfcf56a2f93");
                _cmbcompaniaInfo = new RepoItemInfo(this, "CmbCompania", "combobox[@controlname='cmbCompania']", 30000, null, "1d88c8c1-4d2b-40ee-868a-34ff3f55d38a");
                _cmblineaInfo = new RepoItemInfo(this, "CmbLinea", "combobox[@controlname='cmbLinea']", 30000, null, "3a6a589f-4d7d-4ae7-b4cb-6b4494802798");
                _cmdaceptarInfo = new RepoItemInfo(this, "CmdAceptar", "button[@controlname='cmdAceptar']", 30000, null, "8de9f300-5f2e-4fba-9376-fd440ad57628");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f0389836-0c1b-49cb-9224-df4011a1986a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f0389836-0c1b-49cb-9224-df4011a1986a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtLogin item.
            /// </summary>
            [RepositoryItem("2e296aac-d056-45f1-8256-85d423b26d33")]
            public virtual Ranorex.Text TxtLogin
            {
                get
                {
                    return _txtloginInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtLogin item info.
            /// </summary>
            [RepositoryItemInfo("2e296aac-d056-45f1-8256-85d423b26d33")]
            public virtual RepoItemInfo TxtLoginInfo
            {
                get
                {
                    return _txtloginInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("61f9105f-2e43-4ada-9a84-edfcf56a2f93")]
            public virtual Ranorex.Text TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("61f9105f-2e43-4ada-9a84-edfcf56a2f93")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The CmbCompania item.
            /// </summary>
            [RepositoryItem("1d88c8c1-4d2b-40ee-868a-34ff3f55d38a")]
            public virtual Ranorex.ComboBox CmbCompania
            {
                get
                {
                    return _cmbcompaniaInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbCompania item info.
            /// </summary>
            [RepositoryItemInfo("1d88c8c1-4d2b-40ee-868a-34ff3f55d38a")]
            public virtual RepoItemInfo CmbCompaniaInfo
            {
                get
                {
                    return _cmbcompaniaInfo;
                }
            }

            /// <summary>
            /// The CmbLinea item.
            /// </summary>
            [RepositoryItem("3a6a589f-4d7d-4ae7-b4cb-6b4494802798")]
            public virtual Ranorex.ComboBox CmbLinea
            {
                get
                {
                    return _cmblineaInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbLinea item info.
            /// </summary>
            [RepositoryItemInfo("3a6a589f-4d7d-4ae7-b4cb-6b4494802798")]
            public virtual RepoItemInfo CmbLineaInfo
            {
                get
                {
                    return _cmblineaInfo;
                }
            }

            /// <summary>
            /// The CmdAceptar item.
            /// </summary>
            [RepositoryItem("8de9f300-5f2e-4fba-9376-fd440ad57628")]
            public virtual Ranorex.Button CmdAceptar
            {
                get
                {
                    return _cmdaceptarInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CmdAceptar item info.
            /// </summary>
            [RepositoryItemInfo("8de9f300-5f2e-4fba-9376-fd440ad57628")]
            public virtual RepoItemInfo CmdAceptarInfo
            {
                get
                {
                    return _cmdaceptarInfo;
                }
            }
        }

        /// <summary>
        /// The AsociacionAnexos_COFAppFolder folder.
        /// </summary>
        [RepositoryFolder("813662be-95b1-4d00-b384-4b5028a6b090")]
        public partial class AsociacionAnexos_COFAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonsiInfo;

            /// <summary>
            /// Creates a new AsociacionAnexos_COF  folder.
            /// </summary>
            public AsociacionAnexos_COFAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AsociacionAnexos_COF", "/form[@title='AsociacionAnexos']", parentFolder, 5000, null, true, "813662be-95b1-4d00-b384-4b5028a6b090", "")
            {
                _buttonsiInfo = new RepoItemInfo(this, "ButtonSi", "button[@text='&Sí']", 1000, null, "11cb3606-fffa-4cdf-9458-c97fdf1643e1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("813662be-95b1-4d00-b384-4b5028a6b090")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("813662be-95b1-4d00-b384-4b5028a6b090")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonSi item.
            /// </summary>
            [RepositoryItem("11cb3606-fffa-4cdf-9458-c97fdf1643e1")]
            public virtual Ranorex.Button ButtonSi
            {
                get
                {
                    return _buttonsiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSi item info.
            /// </summary>
            [RepositoryItemInfo("11cb3606-fffa-4cdf-9458-c97fdf1643e1")]
            public virtual RepoItemInfo ButtonSiInfo
            {
                get
                {
                    return _buttonsiInfo;
                }
            }
        }

        /// <summary>
        /// The Advertencia_COFAppFolder folder.
        /// </summary>
        [RepositoryFolder("0b173e44-3415-4599-9183-d12ff220b9f2")]
        public partial class Advertencia_COFAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aceptarInfo;

            /// <summary>
            /// Creates a new Advertencia_COF  folder.
            /// </summary>
            public Advertencia_COFAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Advertencia_COF", "/form[@title='Advertencia']", parentFolder, 3000, null, true, "0b173e44-3415-4599-9183-d12ff220b9f2", "")
            {
                _aceptarInfo = new RepoItemInfo(this, "Aceptar", "button[@text='Aceptar']", 0, null, "e8a1116d-8381-46e9-a580-2893a7236e47");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0b173e44-3415-4599-9183-d12ff220b9f2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0b173e44-3415-4599-9183-d12ff220b9f2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Aceptar item.
            /// </summary>
            [RepositoryItem("e8a1116d-8381-46e9-a580-2893a7236e47")]
            public virtual Ranorex.Button Aceptar
            {
                get
                {
                    return _aceptarInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Aceptar item info.
            /// </summary>
            [RepositoryItemInfo("e8a1116d-8381-46e9-a580-2893a7236e47")]
            public virtual RepoItemInfo AceptarInfo
            {
                get
                {
                    return _aceptarInfo;
                }
            }
        }

        /// <summary>
        /// The FrmReprocesoAppFolder folder.
        /// </summary>
        [RepositoryFolder("cb7a21fc-2488-4452-b687-17aa99985734")]
        public partial class FrmReprocesoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _btnguardarInfo;

            /// <summary>
            /// Creates a new FrmReproceso  folder.
            /// </summary>
            public FrmReprocesoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmReproceso", "/form[@controlname='FrmReproceso']", parentFolder, 30000, null, true, "cb7a21fc-2488-4452-b687-17aa99985734", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "0e8d4c2f-bcc5-4cbe-bd7a-2888a3953fd5");
                _btnguardarInfo = new RepoItemInfo(this, "BtnGuardar", "button[@controlname='btnGuardar']", 30000, null, "80dd1ee7-df12-422a-aca1-874ee21880ad");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cb7a21fc-2488-4452-b687-17aa99985734")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cb7a21fc-2488-4452-b687-17aa99985734")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("0e8d4c2f-bcc5-4cbe-bd7a-2888a3953fd5")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("0e8d4c2f-bcc5-4cbe-bd7a-2888a3953fd5")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The BtnGuardar item.
            /// </summary>
            [RepositoryItem("80dd1ee7-df12-422a-aca1-874ee21880ad")]
            public virtual Ranorex.Button BtnGuardar
            {
                get
                {
                    return _btnguardarInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnGuardar item info.
            /// </summary>
            [RepositoryItemInfo("80dd1ee7-df12-422a-aca1-874ee21880ad")]
            public virtual RepoItemInfo BtnGuardarInfo
            {
                get
                {
                    return _btnguardarInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
