///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MenuPaso1 recording.
    /// </summary>
    [TestModule("f4011883-0f97-4123-8a92-e364958670f0", ModuleType.Recording, 1)]
    public partial class MenuPaso1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static MenuPaso1 instance = new MenuPaso1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MenuPaso1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MenuPaso1 Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable MenuItem.
        /// </summary>
        [TestVariable("aabc01ea-ec93-4de2-ab96-733731c89f7e")]
        public string MenuItem
        {
            get { return repo.MenuItem; }
            set { repo.MenuItem = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ItemProducto.
        /// </summary>
        [TestVariable("12f92637-d732-4177-a3da-8a9594b97f83")]
        public string ItemProducto
        {
            get { return repo.ItemProducto; }
            set { repo.ItemProducto = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Archivo' at 22;13.", repo.MDIPrincipal.ArchivoInfo, new RecordItemIndex(0));
            repo.MDIPrincipal.Archivo.Click("22;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IQCuentasMedicas.CapturaAtencionesYServicios' at 77;15.", repo.IQCuentasMedicas.CapturaAtencionesYServiciosInfo, new RecordItemIndex(1));
            repo.IQCuentasMedicas.CapturaAtencionesYServicios.Click("77;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.CboProductos' at 61;6.", repo.MDIPrincipal.CboProductosInfo, new RecordItemIndex(2));
            repo.MDIPrincipal.CboProductos.Click("61;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.CuentasMedicas' at 53;5.", repo.List1000.CuentasMedicasInfo, new RecordItemIndex(3));
            repo.List1000.CuentasMedicas.Click("53;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.BtnInicio' at 64;6.", repo.MDIPrincipal.BtnInicioInfo, new RecordItemIndex(4));
            repo.MDIPrincipal.BtnInicio.Click("64;6");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
